language: go

sudo: false

go:
    - 1.4
    - 1.5
    - 1.6
    - tip

before_install:
    - go get github.com/smartystreets/goconvey

install:
    - go get -t -d -v ./...
    - go build -v

script:
    - go test -v -race ./...
